stages:
  - tests
  - build
  - name: deploy
    if: branch = master
dist: trusty
language: node_js
node_js:
- 9
services:
- mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
install: true
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
# Default steps within each job
before_install:
- phpenv global 7.1.11
- mysql -e 'CREATE DATABASE IF NOT EXISTS strong;'
- cp config/secrets.env.js.example config/secrets.env.js
- git clone "https://github.com/darrynten/strong-lumen" --branch=master ../strong-lumen
- cd ../strong-lumen
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan migrate
- php artisan db:seed
- pwd
- touch ./storage/logs/lumen.log
- sudo chmod 777 ./storage/logs/lumen.log
- nohup php -S 127.0.0.1:8000 -t public &
- cd -
- npm install
jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script: npm run unit
      after_success:
        - codecov test/unit/coverage/lcov.info -t ${CODECOV_TOKEN}
        - echo "Done"
    - stage: tests
      name: "Cypress Tests"
      script: ./scripts/setup_cypress.sh && npm run dev && $(npm bin)/cypress run
    - stage: build
      name: "Build"
      script: npm run build
    - stage: deploy
      name: "No Target"
      before_install: true
      script: echo Add deployment settings!
